name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '6 6 * * *'

jobs:
  docker:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          DOCKER_USER=${{ secrets.DOCKER_HUB_USERNAME }} DOCKER_PASSWORD=${{ secrets.DOCKER_HUB_TOKEN }} \
            DOCKER_IMAGE_PREFIX=${{ secrets.DOCKER_IMAGE_PREFIX }} ./build.sh
